version: '3.8'
services:
  web:
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    networks:
      - my_network
    image: postgres:14  # Используем образ PostgreSQL
    restart: always
    ports:
      - "5432:5432"  # Порт для PostgreSQL
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Инициализационный SQL файл
      - postgres-db:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres-db:
    driver: local
