FROM yiisoftware/yii2-php:8.0-apache


RUN apt-get update
# Установка необходимых расширений для PostgreSQL
RUN apt-get install -y libpq-dev

# Копируем проект в контейнер
COPY . /app

# Устанавливаем права на папки
RUN chown -R www-data:www-data /app/runtime /app/web/assets

# Устанавливаем рабочую директорию
WORKDIR /app
