version: '3.8'
services:
  web:
    networks:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    networks:
      - postgres
    image: postgres:14  # Используем образ PostgreSQL
    restart: always
    ports:
      - "5432:5432"  # Порт для PostgreSQL
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Инициализационный SQL файл

networks:
  postgres:
    driver: bridge
